[package]
authors = ["Billy Rieger <wrieger93@gmail.com>"]
categories = ["data-structures", "algorithms"]
description = "A fast two-way bijective map implementation"
documentation = "https://docs.rs/bimap/"
homepage = "https://github.com/wrieger93/bimap-rs/"
keywords = ["bijection", "bidirectional", "map", "container", "two-way"]
license = "Apache-2.0"
name = "bimap"
readme = "README.md"
repository = "https://github.com/wrieger93/bimap-rs/"
version = "0.1.5"

[features]
default = ["std"]
std = []

[dependencies]
cfg-if = "0.1"
